.TH RBLCHECK "1" "August 2004" "rblcheck 1.5-20020316" "User Commands"
.SH NAME
rblcheck \- check if an IP address is blacklisted
.SH SYNOPSIS
.B rblcheck
[\fI-qtlcvh?\fR] [\fI-s <service>\fR] \fI<address> \fR[ \fI<address> \fR... ]
.SH DESCRIPTION

.B rblcheck
is a very basic interface to DNSBL listings such as those operated by
The Spamhaus Project or Spamcop.

The general idea behind DNSBL listings is rapid lookup of IP
addresses using DNS (for example, for blacklisting IP addresses
because of abuse). Each IP address is reversed and has a domain name
attached to it; for example, the IP address 127.0.0.2 would become
2.0.0.127, and then a domain such as "relays.visi.com" would be added
to it. You would then try to resolve the result (ie.
2.0.0.127.relays.visi.com); if you receive a positive reply, then you
know that the address is listed. Further information can also be
queried, such as text descriptions of why the address was listed.

.SH OPTIONS
.TP
\fB\-q\fR
Quiet mode; outputs only matching IP address(es) - use return code (see
below).
.TP
\fB\-t\fR
Print a TXT record, if any.
.TP
\fB\-m\fR
Stop checking after first address match in any list.
.TP
\fB\-l\fR
List default DNSBL services to check.
.TP
\fB\-c\fR
Clear the current list of DNSBL services.
.TP
\fB\-s\fR \fI<service>\fR
Toggle
.I service
in the DNSBL list.
.TP
\fB\-h, -?\fR
Display the help message.
.TP
\fB\-v\fR
Display version information.
.TP
\fB<address>\fR
An IP address to look up; specify `-' to read multiple addresses from
standard input.

.SH "RETURN CODES"
When invoked, 
.B rblcheck
returns either 0 (to indicate error, or that
the address was not in any of the listings), or a positive number
(indicating the number of listings that the IP address was found in).

.SH "SEE ALSO"
\fB/usr/share/doc/rblcheck/\fR, esp. \fB/usr/share/doc/rblcheck/rblcheck.txt.gz\fR
.SH COPYRIGHT
Copyright \(co 1997, 1998, 1999, 2000, 2001 Edward S. Marshall
.PP
Man page created for the Debian Project with the help of
.BR help2man (1)
based on the output of `rblcheck -h` and the above mentioned text file by
Gregor Herrmann <gregor+debian@comodo.priv.at>.
